build:
  image: python:3.9-slim
  command: pip install -r requirements.txt && python -m flask db upgrade && python init_db.py
  publish: "."
  environment:
    FLASK_ENV: production
    FLASK_DEBUG: "False"

functions:
  directory: api

plugins:
  - package: "@netlify/plugin-functions-install-core"
